name = "studyplaner-api"
main = "src/main.py"
compatibility_date = "2025-05-20"
compatibility_flags = ["python_workers"]
workers_dev = true

[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "https://studyplaner.pages.dev,http://localhost:5173"

[[d1_databases]]
binding = "DB"
database_name = "studyplaner-db-test"
database_id = "297f7a28-9069-431d-b989-49acf2537513"
